### ISSUE TITLE
Task: EDA

### ISSUE THREAD

**Issue by rishisahoo** [rishisahoo/energy#15]
Plot boxplots to visually inspect the distribution of each feature.
Code is added to this file

Supports Story #5

**Comment by CadeKolanowski** [comment]
Subtasks: This task creates a box plot for the data in the data set.
1: plt.figure(figsize(15,10)) makes the figure 15 inches by 10 inches
2: df.boxplot(column=['Relative_Compactness', 'Surface_Area', 'Wall_Area', 'Roof_Area',
                   'Overall_Height', 'Heating_Load', 'Cooling_Load']) creates the box plot with labels 
3: plt.title("Boxplot of Architectural Features and Target Variables") creates a title so the view can understand what exactly is being presented
4: plt.xticks(rotation=45) rotates the labels by 45 degrees for it to be easier to read
5 plt.show() shows the plot with everything listed
