### ISSUE TITLE
Task: Evaluation

### ISSUE THREAD

**Issue by rishisahoo** [rishisahoo/energy#16]
Evaluate the model's performance using R² score and Mean Absolute Error.
Code is added to this file

Supports Story #8

**Comment by CadeKolanowski** [comment]
Subtask: This task evaluates the performance of the Heating Load model and the Cooling Load model using R^2 score and Mean Absolute Error
1: print("Heating Load Model Evaluation:")
print("R² Score:", r2_score(y_test_h, y_pred_h)) prints the calculation score of the R^2 between the testing data and the predicted data of the Heating Load dataset
2: print("Mean Absolute Error:", mean_absolute_error(y_test_h, y_pred_h)) prints the calculated value of the Mean Absolute Error of the Heating Load dataset
3: print("\nCooling Load Model Evaluation:")
print("R² Score:", r2_score(y_test_c, y_pred_c)) the same is done for the Cooling Load dataset
4: print("Mean Absolute Error:", mean_absolute_error(y_test_c, y_pred_c)) the same is done for the Cooling Load dataset
