### ISSUE TITLE
Task: Readability

### ISSUE THREAD

**Issue by rishisahoo** [rishisahoo/energy#17]
Task 2: Change names for readability

Supports Story #18

**Comment by CadeKolanowski** [comment]
Subtasks: The task renames the columns of the Data Frame for clarity
1: df.columns lists the columns to be changed
2. [
    'Relative_Compactness', 'Surface_Area', 'Wall_Area', 'Roof_Area',
    'Overall_Height', 'Orientation', 'Glazing_Area',
    'Glazing_Area_Distribution', 'Heating_Load', 'Cooling_Load'
]  assigns the columns the names listed
3: df.columns = [
    'Relative_Compactness', 'Surface_Area', 'Wall_Area', 'Roof_Area',
    'Overall_Height', 'Orientation', 'Glazing_Area',
    'Glazing_Area_Distribution', 'Heating_Load', 'Cooling_Load'
] applies the changes we listed and renames the columns of the Data Frame
