### ISSUE TITLE
Task: Scaling the Features

### ISSUE THREAD

**Issue by rishisahoo** [rishisahoo/energy#20]
Scaling the features can help make sure that all features are one a similar scale.

Supports Story #19

**Comment by CadeKolanowski** [comment]
Subtasks: This task is used to scale the features of the dataset of both Heating Load and Cooling Load, which is important for improving performance
1: scaler = StandardScaler() creates a StandardScaler from the scikit-learn module to provide a range
2: X_train_h = scaler.fit_transform(X_train_h) applies the StandardScaler to the training data from 'Heating_Load'
3: X_test_h = scaler.transform(X_test_h) applies the StandardScaler to the testing data from 'Heating_Load'
4: X_train_c = scaler.fit_transform(X_train_c) the same is done for the training data for 'Cooling_Load'
5: X_test_c = scaler.transform(X_test_c) the same is done for the testing data for 'Cooling_Load'
