### ISSUE TITLE
Task: Features and Targets

### ISSUE THREAD

**Issue by rishisahoo** [rishisahoo/energy#22]
Features are the input variables (independent variables) used to make predictions, while targets are the output variables (dependent variables) that the model aims to predict. We aim to incorporate this in our code.

Supports Story #21

**Comment by CadeKolanowski** [comment]
Subtasks: The task defines independent (Features) and dependent (Targets) variables in the code.
1: X = df[['Relative_Compactness', 'Surface_Area', 'Wall_Area', 'Roof_Area',
        'Overall_Height', 'Orientation', 'Glazing_Area', 'Glazing_Area_Distribution']] sets columns in the Data Frame as Features
2: y_heating = df['Heating_Load'] sets the 'Heating_Load' column as a Target
3: y_cooling = df['Cooling_Load'] sets the 'Cooling_Load' column as a Target as well
